export const tableHeader = [
	{
		accessor: " ",
        Header: "", // Empty string for the first column
        isTooltip: false,
        isSortingEnabled: false,
	},
	{
		accessor: "ticker",
		Header: "Ticker",
		isTooltip: true,
		isSortingEnabled: false,
		tooltipLabel: "Ticker",
	},
	{
		accessor: "issuer",
		Header: "Issuer",
		isTooltip: true,
		isSortingEnabled: false,
		tooltipLabel: "Issuer",
	},
	{
		accessor: "etf name",
		Header: "ETF Name",
		isTooltip: true,
		isSortingEnabled: false,
		tooltipLabel: "ETF Name",
	},
	{
		accessor: "type",
		Header: "Type",
		isTooltip: true,
		isSortingEnabled: false,
		tooltipLabel: "Type",
	},
	{
		accessor: "share(usd)",
		Header: "Share(USD)",
		isTooltip: true,
		isSortingEnabled: false,
		tooltipLabel: "Share(USD)",
	},
	{
		accessor: "share(sats)",
		Header: "Share(sats)",
		isTooltip: true,
		isSortingEnabled: false,
		tooltipLabel: "Share(sats)",
	},
	{
		accessor: "custodian",
		Header: "Custodian",
		isTooltip: true,
		isSortingEnabled: false,
		tooltipLabel: "Custodian",
	},
	{
		accessor: "volume(24h)",
		Header: "Volume(24h)",
		isTooltip: true,
		isSortingEnabled: false,
		tooltipLabel: "Volume(24h)",
	},
    {
		accessor: "volume(btc)",
		Header: "Volume(BTC)",
		isTooltip: true,
		isSortingEnabled: false,
		tooltipLabel: "Volume(BTC)",
	},
    {
		accessor: "status",
		Header: "Status",
		isTooltip: true,
		isSortingEnabled: false,
		tooltipLabel: "Status",
	},
];