/* eslint-disable react/no-unescaped-entities */
/* eslint-disable max-len */
"use client";
import { Box, Text, useColorModeValue } from "@chakra-ui/react";
import React from "react";

const PrivacyPanelComponent = () => {
	return (
		<>
			<Box>
				<Box
					display={{ base: "none", md: "block" }}
					width={"100%"}
					background={useColorModeValue("#F0F0F5", "#191919")}
					padding={"35px 150px 70px 72px"}>
					<Text variant={"contentHeading3"} fontWeight={"600"}>1. INTRODUCTION</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        Welcome to BetygFi (referred to as “the Platform” or “we” or “our” or “us”). This Privacy Policy governs your visit to the Platform, it explains how we process your personal digital data which includes collection, safeguarding, disclosure and use of information that results from your use of BetygFi.
						<br />
						<br />
                        BetygFi processes your data to provide and improve its services. By using BetygFi and agreeing to the Terms and Conditions of BetygFi you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
						<br />
						<br />
                        Our Terms and Conditions (“Terms”) govern the use of our Service. The Privacy Policy is part and parcel of the Terms and is part of your agreement with us (“agreement”).
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>2. DEFINITIONS</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        Personal Data means information about a living individual who can be identified from such information.
						<br />
						<br />
                        Usage Data is information collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).
						<br />
						<br />
                        User is the individual and/or natural person using BetygFi's Service
						<br />
						<br />
                        Service(s) means all the services provided by BetygFi.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>3. PERSONAL DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        While using BetygFi we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:
					</Text>
					<Box padding={"10px 0px 0px 45px"}>
						<ul>
							<li>
								<Text variant={"content"}>Personal details such as name, email address, mobile telephone contact details including residential address, date of birth, provided by you to us to avail various products/services from us. We may also collect our wallet address to help you enable our services.</Text>
							</li>
							<li>
								<Text variant={"content"}>Technical Data: including internet protocol (IP) address, your login data, traffic data, browser type and version, time zone setting and location, browser plug-in types and versions, operating system, and platform and other communication data which gives us information about how you accessed our website. Other account information and usage information including your IP address and browser data may be used for diagnosis, security, and Product and Service optimization.</Text>
							</li>
							<li>
								<Text variant={"content"}>Specimen signature(s) for processing of your instructions received by us through our various payment and delivery channels;</Text>
							</li>
							<li>
								<Text variant={"content"}>Information obtained from your mobile device by way of using our app like device location, communication information including contacts and call logs, device information (including storage, model, mobile network), transactional and promotional SMS/app notifications.</Text>
							</li>
						</ul>
					</Box>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>4. USAGE DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        We also use your Personal Data to fulfill the requirements of applicable laws/regulations and/or court orders/regulatory directives received by us. We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (“Usage Data”).
						<br />
						<br />
                        This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
						<br />
						<br />
                        When you access BetygFi and/or its Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>5. TRACKING COOKIES DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        BetygFi may use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
						<br />
						<br />
                        Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies may also be used by us to collect and track information and to improve and analyse our Service.
						<br />
						<br />
                        You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>6. USE OF PERSONAL DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        BetygFi makes use of Personal Data, Technical Data or other related data to provide its services viz. the following (the list below is indicative and not exhaustive):
					</Text>
					<Box padding={"10px 0px 0px 45px"}>
						<ul>
							<li>
								<Text variant={"content"}>To collect and process such data- necessary to produce such work product that would be beneficial to you.</Text>
							</li>
							<li>
								<Text variant={"content"}>To provide and maintain Services.</Text>
							</li>
							<li>
								<Text variant={"content"}>To undertake research and analytics for offering or improving our products/services and their security and service quality.</Text>
							</li>
							<li>
								<Text variant={"content"}>To share with you, updates on changes to the products/services and their terms and conditions.</Text>
							</li>
							<li>
								<Text variant={"content"}>To gather analysis or valuable information so that we can improve our Service.</Text>
							</li>
							<li>
								<Text variant={"content"}>To detect, prevent and address technical issues.</Text>
							</li>
							<li>
								<Text variant={"content"}>To verify your identity for us to be able to secure and protect your personal data.</Text>
							</li>
							<li>
								<Text variant={"content"}>To carry checks, screenings or due diligence checks as lawfully required by us and/or that we may deem fit and/or necessary.</Text>
							</li>
							<li>
								<Text variant={"content"}>To monitor and review products/services from time to time.</Text>
							</li>
							<li>
								<Text variant={"content"}>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information.</Text>
							</li>
							<li>
								<Text variant={"content"}>To carry out our obligations and enforce our rights arising from any contracts entered into between you and us.</Text>
							</li>
							<li>
								<Text variant={"content"}>For the performance by the State or any of its instrumentalities of any function under any law for the time being in force in India or in the interest of sovereignty and integrity of India or security of the State.</Text>
							</li>
							<li>
								<Text variant={"content"}>For fulfilling any obligation under any law for the time being in force in India on any person to disclose any information to the State or any of its instrumentalities, subject to such processing being in accordance with the provisions regarding disclosure of such information in any other law for the time being in force.</Text>
							</li>
							<li>
								<Text variant={"content"}>For compliance with any judgment or decree or order issued under any law for the time being in force in India, or any judgment or order relating to claims of a contractual or civil nature under any law for the time being in force outside India.</Text>
							</li>
							<li>
								<Text variant={"content"}>In any other way we may describe when you provide the information.</Text>
							</li>
							<li>
								<Text variant={"content"}>For any other purpose with your consent.</Text>
							</li>
						</ul>
					</Box>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>7. INTELLECTUAL PROPERTY</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        This Agreement does not transfer to You any intellectual property owned by BetygFi. All rights, titles, and interests will remain the exclusive property of BetygFi and its licensors. All trademarks, Service marks, graphics, logos, visual interfaces, graphics, design, compilation, information, computer code (including source code and object code), products, software, Services, and all other elements used in connection with BetygFi, work product produced by BetygFi, information collected/analyzed by BetygFi, are property/trademarks/ registered trademarks of BetygFi and/or its licensors and/or its assigns. The said Services are protected by relevant copyright, trade, patent, and trademark laws, international conventions, and all other relevant intellectual property and proprietary rights, and applicable laws. Your use of BetygFi and its Services grants You no right or license to reproduce or otherwise use any of the trademarks of BetygFi. You agree not to sell, license, distribute, copy, modify, publicly perform or display, transmit, publish, edit, adapt, create derivative works from, or otherwise make unauthorized use of the Materials. BetygFi reserves all rights not expressly granted in this Agreement.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>8. HYPERLINKING TO OUR CONTENT</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        Our Service may contain links to third-party web sites or Services that are not owned or controlled by the Company.
						<br />
						<br />
                        The Company has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or Services. You further acknowledge and agree that BetygFi shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or Services available on or through any such web sites or Services.
						<br />
						<br />
                        We strongly advise You to read the terms and conditions and privacy policies of any third-party web sites or Services that You visit.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>9. PROHIBITED ACTIVITIES</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        BetygFi is not responsible for any damages resulting from use of this Platform by anyone. You will not use the Platform for illegal purposes. You will:
					</Text>
					<Box padding={"10px 0px 0px 45px"}>
						<ul>
							<li>
								<Text variant={"content"}>Abide by all applicable local, state, national, and international laws and regulations in your use of BetygFi (including laws regarding intellectual property).</Text>
							</li>
							<li>
								<Text variant={"content"}>Abide by all applicable local, state, national, and international laws and regulations in your use of BetygFi (including laws regarding intellectual property).</Text>
							</li>
							<li>
								<Text variant={"content"}>Not interfere with or disrupt the use and enjoyment of the BetygFi by other users.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not defame, harass, abuse, or disrupt other users and constituents of BetygFi.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not impersonate or attempt to impersonate BetygFi, employees of BetygFi, another user, or any other person or entity.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not in any way infringe upon the rights of others or engage in activity that is in any way illegal, threatening, fraudulent, or harmful.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not use BetygFi in any manner that could disable, overburden, damage, or impair its Service(s) or interfere with any other party's use of BetygFi and/or its Service, including their ability of such third parties to engage in real time activities through Service.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not use any robot, spider, or other automatic device, process, or means to access Service for any purpose, including monitoring or copying any of the material on Service.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not use any device, software, or routine that interferes with the proper working of BetygFi or its Service.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not introduce any viruses, trojan horses, worms, logic bombs, or other material which is malicious or technologically harmful.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of Service, the server on which Service is stored, or any server, computer, or database connected to Service.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not take any action that may damage or falsify the Platform rating.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not otherwise attempt to interfere with the proper working of BetygFi or its Service.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not forge headers or manipulate identifiers or other data in order to disguise the origin of any content transmitted through BetygFi or to manipulate and/or mask your presence on BetygFi.</Text>
							</li>
							<li>
								<Text variant={"content"}>Sell services being offered by BetygFi, data and/or information and/or software and/or derivatives of the services, data, information, software belonging to BetygFi.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not commit breach of this Agreement, or any other agreement or policy as may be applicable pursuant to the Terms and Conditions.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not avail the Services of BetygFi with funds that may be qualified as potentially fraudulent funds; such qualification shall be the discretion of BetygFi.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not use the Services of BetygFi in a manner that results in or may result in complaints, disputes, reversals, chargebacks, fees, fines, penalties and other liability to BetygFi, a third party or You.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not use the Services of BetygFi in a manner that BetygFi or any payment card network reasonably believe to be an abuse of the payment card system or a violation of payment card network rules.</Text>
							</li>
						</ul>
					</Box>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>10. EXTERNAL PROCESSING</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        We may provide your Personal Data to our affiliates or other trusted businesses or persons or service providers engaged by us, or to institutions that we partner with to assist us with providing you with products/services to better serve your needs and interests, based on your instructions and in compliance with our Privacy Policy and any other appropriate confidentiality and security measures.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>11. RETENTION OF DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
						<br />
						<br />
                        We obtain your wallet ID, that is both wholly and/or in part - public and/or proprietary in nature. The said information is assimilated and processed for producing such work product that is beneficial to you.
						<br />
						<br />
                        All data provided to BetygFi and derivatives of such data shall be the proprietary of BetygFi. You hereby grant BetygFi and/or its assigns absolute authority as and by way of a license or any such enforceable instrument as per the laws of India to enable BetygFi to absolute use and authority of the Personal Data by BetygFi from you. Your acceptance of the Terms and Conditions of BetygFi and engagement of BetygFi for producing work product and/or your subscription of the Services provided by BetygFi, irrespective of any additional consideration made by you to BetygFi and/or its' affiliates - shall be adequate consideration for transfer of rights in such Personal Data to BetigFi and/or its assigns. This data will be used by BetygFi and/or its assigns to produce work product and/or provide Service(s) and shall be used for improvement of the Service(s) of BetygFi from time to time.
						<br />
						<br />
                        We will retain Usage Data for internal analysis purposes. Usage Data is retained for when this data is used to strengthen security of our Service or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>12. TRANSFER OF DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        Your information may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
						<br />
						<br />
                        Your consent to this Privacy Policy followed by your submission of such information including but not limited to Personal Data represents your agreement to that transfer.
						<br />
						<br />
                        BetygFi will take all the steps reasonably necessary to ensure that your Personal Data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>13. DISCLOSURE OF DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        We may disclose personal information that we collect, or you provide:
					</Text>
					<Box padding={"10px 0px 0px 45px"}>
						<ul>
							<li>
								<Text variant={"content"}>Disclosure for Law Enforcement.</Text>
							</li>
						</ul>
						<Text variant={"content"} paddingTop={"10px"} paddingLeft={"20px"}>
                            Under certain circumstances, we may be required to disclose your Personal Data, Technical Data and Usage Data if required to do so by law or in response to valid requests by public authorities.
						</Text>
					</Box>
					<Box padding={"10px 0px 0px 45px"}>
						<ul>
							<li>
								<Text variant={"content"}>Business Transaction.</Text>
							</li>
						</ul>
						<Text variant={"content"} paddingTop={"10px"} paddingLeft={"20px"}>
                            If BetygFi or its parent company or its sister concerns or its subsidiaries are involved in a merger, acquisition or asset sale or in a transaction that has the effect of a merger, acquisition or asset sale - your Personal Data, Technical Data and Usage Data may be transferred as per the terms of such merger, acquisition or asset sale. In such event BetygFi and/or the resulting entity and/or any such entity shall be bound by all agreements with you including this Privacy Policy.
						</Text>
					</Box>
					<Box padding={"10px 0px 0px 45px"}>
						<ul>
							<li>
								<Text variant={"content"}>Other cases.</Text>
							</li>
						</ul>
						<Text variant={"content"} paddingTop={"10px"} paddingLeft={"20px"}>
                            BetygFi may disclose and use Personal Data:
						</Text>
					</Box>
					<Box padding={"10px 0px 0px 100px"}>
						<ul style={{ listStyleType: "lower-alpha" }}>
							<li>
								<Text variant={"content"}>To our parent company, sister company, subsidiaries and affiliates.</Text>
							</li>
							<li>
								<Text variant={"content"}>To contractors, service providers, and other third parties we use to support our business.</Text>
							</li>
							<li>
								<Text variant={"content"}>To fulfill the purpose for which you provide it.</Text>
							</li>
							<li>
								<Text variant={"content"}>Or any other purpose disclosed by us when you provide the information.</Text>
							</li>
							<li>
								<Text variant={"content"}>With your consent in any other cases.</Text>
							</li>
							<li>
								<Text variant={"content"}>If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</Text>
							</li>
						</ul>
					</Box>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>14. ERASURE AND MODIFICATION OF YOUR PERSONAL DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        You shall have the right to correction, completion, updating and erasure of your personal data for the processing of which you have previously given consent. With this we will no longer provide your Personal Data for external processing as mentioned above. However, we may retain your Personal Data as long as the purpose for its usage exists, after which the same is disposed of by us except for any record retention required as per applicable law.
						<br />
						<br />
                        Further, in the event of the pendency of any legal/regulatory proceeding or receipt of any legal and/or regulatory direction to that effect, we may be required by the law of the land to retain your Personal Data for longer periods.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>15. SECURITY OF DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        The security of all your data is important to us and we shall make best in industry efforts to keep all your data secure. But remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect all your Data including your Personal Data, however we cannot guarantee its absolute security.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>16. SERVICE PROVIDERS</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        BetygFi may employ third party companies and individuals (“Service Providers”) to facilitate our Service, provide Service on our behalf, perform Service-related services or assist us in analyzing how our Service is used. These third parties have access to your Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>17. REASONABLE SECURITY PRACTICES AND PROCEDURES</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        BetygFi takes various steps and measures to protect the security of your Personal Data from misuse, loss, unauthorized access, modification or disclosure. We use latest secure server layers encryption and access control on our systems.
						<br />
						<br />
                        Our safety and security processes are audited by a third party cyber security audit agency from time to time.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>18. LINKS TO OTHER SITES</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
						<br />
						<br />
                        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>19. CHANGES TO THIS PRIVACY POLICY</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
						<br />
						<br />
                        We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.
						<br />
						<br />
                        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
					</Text>
				</Box>

				{/* Mobile Optimization Part */}

				<Box
					display={{ base: "block", md: "none" }}
					background={useColorModeValue("#F0F0F5", "#191919")}
					padding={"22px 15px 95px 15px"}>
					<Text variant={"contentHeading3"} fontWeight={"600"}>1. INTRODUCTION</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        Welcome to BetygFi (referred to as “the Platform” or “we” or “our” or “us”). This Privacy Policy governs your visit to the Platform, it explains how we process your personal digital data which includes collection, safeguarding, disclosure and use of information that results from your use of BetygFi.
						<br />
						<br />
                        BetygFi processes your data to provide and improve its services. By using BetygFi and agreeing to the Terms and Conditions of BetygFi you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
						<br />
						<br />
                        Our Terms and Conditions (“Terms”) govern the use of our Service. The Privacy Policy is part and parcel of the Terms and is part of your agreement with us (“agreement”).
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>2. DEFINITIONS</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        Personal Data means information about a living individual who can be identified from such information.
						<br />
						<br />
                        Usage Data is information collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).
						<br />
						<br />
                        User is the individual and/or natural person using BetygFi's Service
						<br />
						<br />
                        Service(s) means all the services provided by BetygFi.
					</Text>

					<Text variant={"contentHeading3"}fontWeight={"600"} paddingTop={"30px"}>3. PERSONAL DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        While using BetygFi we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:
					</Text>
					<Box padding={"10px 0px 0px 25px"}>
						<ul>
							<li>
								<Text variant={"content"}>Personal details such as name, email address, mobile telephone contact details including residential address, date of birth, provided by you to us to avail various products/services from us. We may also collect our wallet address to help you enable our services.</Text>
							</li>
							<li>
								<Text variant={"content"}>Technical Data: including internet protocol (IP) address, your login data, traffic data, browser type and version, time zone setting and location, browser plug-in types and versions, operating system, and platform and other communication data which gives us information about how you accessed our website. Other account information and usage information including your IP address and browser data may be used for diagnosis, security, and Product and Service optimization.</Text>
							</li>
							<li>
								<Text variant={"content"}>Specimen signature(s) for processing of your instructions received by us through our various payment and delivery channels;</Text>
							</li>
							<li>
								<Text variant={"content"}>Information obtained from your mobile device by way of using our app like device location, communication information including contacts and call logs, device information (including storage, model, mobile network), transactional and promotional SMS/app notifications.</Text>
							</li>
						</ul>
					</Box>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>4. USAGE DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        We also use your Personal Data to fulfill the requirements of applicable laws/regulations and/or court orders/regulatory directives received by us. We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (“Usage Data”).
						<br />
						<br />
                        This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
						<br />
						<br />
                        When you access BetygFi and/or its Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>5. TRACKING COOKIES DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        BetygFi may use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
						<br />
						<br />
                        Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies may also be used by us to collect and track information and to improve and analyse our Service.
						<br />
						<br />
                        You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>6. USE OF PERSONAL DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        BetygFi makes use of Personal Data, Technical Data or other related data to provide its services viz. the following (the list below is indicative and not exhaustive):
					</Text>
					<Box padding={"10px 0px 0px 25px"}>
						<ul>
							<li>
								<Text variant={"content"}>To collect and process such data- necessary to produce such work product that would be beneficial to you.</Text>
							</li>
							<li>
								<Text variant={"content"}>To provide and maintain Services.</Text>
							</li>
							<li>
								<Text variant={"content"}>To undertake research and analytics for offering or improving our products/services and their security and service quality.</Text>
							</li>
							<li>
								<Text variant={"content"}>To share with you, updates on changes to the products/services and their terms and conditions.</Text>
							</li>
							<li>
								<Text variant={"content"}>To gather analysis or valuable information so that we can improve our Service.</Text>
							</li>
							<li>
								<Text variant={"content"}>To detect, prevent and address technical issues.</Text>
							</li>
							<li>
								<Text variant={"content"}>To verify your identity for us to be able to secure and protect your personal data.</Text>
							</li>
							<li>
								<Text variant={"content"}>To carry checks, screenings or due diligence checks as lawfully required by us and/or that we may deem fit and/or necessary.</Text>
							</li>
							<li>
								<Text variant={"content"}>To monitor and review products/services from time to time.</Text>
							</li>
							<li>
								<Text variant={"content"}>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information.</Text>
							</li>
							<li>
								<Text variant={"content"}>To carry out our obligations and enforce our rights arising from any contracts entered into between you and us.</Text>
							</li>
							<li>
								<Text variant={"content"}>For the performance by the State or any of its instrumentalities of any function under any law for the time being in force in India or in the interest of sovereignty and integrity of India or security of the State.</Text>
							</li>
							<li>
								<Text variant={"content"}>For fulfilling any obligation under any law for the time being in force in India on any person to disclose any information to the State or any of its instrumentalities, subject to such processing being in accordance with the provisions regarding disclosure of such information in any other law for the time being in force.</Text>
							</li>
							<li>
								<Text variant={"content"}>For compliance with any judgment or decree or order issued under any law for the time being in force in India, or any judgment or order relating to claims of a contractual or civil nature under any law for the time being in force outside India.</Text>
							</li>
							<li>
								<Text variant={"content"}>In any other way we may describe when you provide the information.</Text>
							</li>
							<li>
								<Text variant={"content"}>For any other purpose with your consent.</Text>
							</li>
						</ul>
					</Box>

					<Text variant={"contentHeading3"}fontWeight={"600"} paddingTop={"30px"}>7. INTELLECTUAL PROPERTY</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        This Agreement does not transfer to You any intellectual property owned by BetygFi. All rights, titles, and interests will remain the exclusive property of BetygFi and its licensors. All trademarks, Service marks, graphics, logos, visual interfaces, graphics, design, compilation, information, computer code (including source code and object code), products, software, Services, and all other elements used in connection with BetygFi, work product produced by BetygFi, information collected/analyzed by BetygFi, are property/trademarks/ registered trademarks of BetygFi and/or its licensors and/or its assigns. The said Services are protected by relevant copyright, trade, patent, and trademark laws, international conventions, and all other relevant intellectual property and proprietary rights, and applicable laws. Your use of BetygFi and its Services grants You no right or license to reproduce or otherwise use any of the trademarks of BetygFi. You agree not to sell, license, distribute, copy, modify, publicly perform or display, transmit, publish, edit, adapt, create derivative works from, or otherwise make unauthorized use of the Materials. BetygFi reserves all rights not expressly granted in this Agreement.
					</Text>

					<Text variant={"contentHeading3"}fontWeight={"600"} paddingTop={"30px"}>8. HYPERLINKING TO OUR CONTENT</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        Our Service may contain links to third-party web sites or Services that are not owned or controlled by the Company.
						<br />
						<br />
                        The Company has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or Services. You further acknowledge and agree that BetygFi shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or Services available on or through any such web sites or Services.
						<br />
						<br />
                        We strongly advise You to read the terms and conditions and privacy policies of any third-party web sites or Services that You visit.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>9. PROHIBITED ACTIVITIES</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        BetygFi is not responsible for any damages resulting from use of this Platform by anyone. You will not use the Platform for illegal purposes. You will:
					</Text>
					<Box padding={"10px 0px 0px 25px"}>
						<ul>
							<li>
								<Text variant={"content"}>Abide by all applicable local, state, national, and international laws and regulations in your use of BetygFi (including laws regarding intellectual property).</Text>
							</li>
							<li>
								<Text variant={"content"}>Abide by all applicable local, state, national, and international laws and regulations in your use of BetygFi (including laws regarding intellectual property).</Text>
							</li>
							<li>
								<Text variant={"content"}>Not interfere with or disrupt the use and enjoyment of the BetygFi by other users.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not defame, harass, abuse, or disrupt other users and constituents of BetygFi.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not impersonate or attempt to impersonate BetygFi, employees of BetygFi, another user, or any other person or entity.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not in any way infringe upon the rights of others or engage in activity that is in any way illegal, threatening, fraudulent, or harmful.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not use BetygFi in any manner that could disable, overburden, damage, or impair its Service(s) or interfere with any other party's use of BetygFi and/or its Service, including their ability of such third parties to engage in real time activities through Service.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not use any robot, spider, or other automatic device, process, or means to access Service for any purpose, including monitoring or copying any of the material on Service.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not use any device, software, or routine that interferes with the proper working of BetygFi or its Service.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not introduce any viruses, trojan horses, worms, logic bombs, or other material which is malicious or technologically harmful.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of Service, the server on which Service is stored, or any server, computer, or database connected to Service.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not take any action that may damage or falsify the Platform rating.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not otherwise attempt to interfere with the proper working of BetygFi or its Service.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not forge headers or manipulate identifiers or other data in order to disguise the origin of any content transmitted through BetygFi or to manipulate and/or mask your presence on BetygFi.</Text>
							</li>
							<li>
								<Text variant={"content"}>Sell services being offered by BetygFi, data and/or information and/or software and/or derivatives of the services, data, information, software belonging to BetygFi.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not commit breach of this Agreement, or any other agreement or policy as may be applicable pursuant to the Terms and Conditions.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not avail the Services of BetygFi with funds that may be qualified as potentially fraudulent funds; such qualification shall be the discretion of BetygFi.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not use the Services of BetygFi in a manner that results in or may result in complaints, disputes, reversals, chargebacks, fees, fines, penalties and other liability to BetygFi, a third party or You.</Text>
							</li>
							<li>
								<Text variant={"content"}>Not use the Services of BetygFi in a manner that BetygFi or any payment card network reasonably believe to be an abuse of the payment card system or a violation of payment card network rules.</Text>
							</li>
						</ul>
					</Box>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>10. EXTERNAL PROCESSING</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        We may provide your Personal Data to our affiliates or other trusted businesses or persons or service providers engaged by us, or to institutions that we partner with to assist us with providing you with products/services to better serve your needs and interests, based on your instructions and in compliance with our Privacy Policy and any other appropriate confidentiality and security measures.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>11. RETENTION OF DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
						<br />
						<br />
                        We obtain your wallet ID, that is both wholly and/or in part - public and/or proprietary in nature. The said information is assimilated and processed for producing such work product that is beneficial to you.
						<br />
						<br />
                        All data provided to BetygFi and derivatives of such data shall be the proprietary of BetygFi. You hereby grant BetygFi and/or its assigns absolute authority as and by way of a license or any such enforceable instrument as per the laws of India to enable BetygFi to absolute use and authority of the Personal Data by BetygFi from you. Your acceptance of the Terms and Conditions of BetygFi and engagement of BetygFi for producing work product and/or your subscription of the Services provided by BetygFi, irrespective of any additional consideration made by you to BetygFi and/or its' affiliates - shall be adequate consideration for transfer of rights in such Personal Data to BetigFi and/or its assigns. This data will be used by BetygFi and/or its assigns to produce work product and/or provide Service(s) and shall be used for improvement of the Service(s) of BetygFi from time to time.
						<br />
						<br />
                        We will retain Usage Data for internal analysis purposes. Usage Data is retained for when this data is used to strengthen security of our Service or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>12. TRANSFER OF DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        Your information may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
						<br />
						<br />
                        Your consent to this Privacy Policy followed by your submission of such information including but not limited to Personal Data represents your agreement to that transfer.
						<br />
						<br />
                        BetygFi will take all the steps reasonably necessary to ensure that your Personal Data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>13. DISCLOSURE OF DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        We may disclose personal information that we collect, or you provide:
					</Text>
					<Box padding={"10px 0px 0px 45px"}>
						<ul>
							<li>
								<Text variant={"content"}>Disclosure for Law Enforcement.</Text>
							</li>
						</ul>
						<Text variant={"content"} paddingTop={"10px"}>
                            Under certain circumstances, we may be required to disclose your Personal Data, Technical Data and Usage Data if required to do so by law or in response to valid requests by public authorities.
						</Text>
					</Box>
					<Box padding={"10px 0px 0px 45px"}>
						<ul>
							<li>
								<Text variant={"content"}>Business Transaction.</Text>
							</li>
						</ul>
						<Text variant={"content"} paddingTop={"10px"}>
                            If BetygFi or its parent company or its sister concerns or its subsidiaries are involved in a merger, acquisition or asset sale or in a transaction that has the effect of a merger, acquisition or asset sale - your Personal Data, Technical Data and Usage Data may be transferred as per the terms of such merger, acquisition or asset sale. In such event BetygFi and/or the resulting entity and/or any such entity shall be bound by all agreements with you including this Privacy Policy.
						</Text>
					</Box>
					<Box padding={"10px 0px 0px 45px"}>
						<ul>
							<li>
								<Text variant={"content"}>Other cases.</Text>
							</li>
						</ul>
						<Text variant={"content"} paddingTop={"10px"}>
                            BetygFi may disclose and use Personal Data:
						</Text>
					</Box>
					<Box padding={"10px 0px 0px 75px"}>
						<ul style={{ listStyleType: "lower-alpha" }}>
							<li>
								<Text variant={"content"}>To our parent company, sister company, subsidiaries and affiliates.</Text>
							</li>
							<li>
								<Text variant={"content"}>To contractors, service providers, and other third parties we use to support our business.</Text>
							</li>
							<li>
								<Text variant={"content"}>To fulfill the purpose for which you provide it.</Text>
							</li>
							<li>
								<Text variant={"content"}>Or any other purpose disclosed by us when you provide the information.</Text>
							</li>
							<li>
								<Text variant={"content"}>With your consent in any other cases.</Text>
							</li>
							<li>
								<Text variant={"content"}>If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</Text>
							</li>
						</ul>
					</Box>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>14. ERASURE AND MODIFICATION OF YOUR PERSONAL DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        You shall have the right to correction, completion, updating and erasure of your personal data for the processing of which you have previously given consent. With this we will no longer provide your Personal Data for external processing as mentioned above. However, we may retain your Personal Data as long as the purpose for its usage exists, after which the same is disposed of by us except for any record retention required as per applicable law.
						<br />
						<br />
                        Further, in the event of the pendency of any legal/regulatory proceeding or receipt of any legal and/or regulatory direction to that effect, we may be required by the law of the land to retain your Personal Data for longer periods.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>15. SECURITY OF DATA</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        The security of all your data is important to us and we shall make best in industry efforts to keep all your data secure. But remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect all your Data including your Personal Data, however we cannot guarantee its absolute security.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>16. SERVICE PROVIDERS</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        BetygFi may employ third party companies and individuals (“Service Providers”) to facilitate our Service, provide Service on our behalf, perform Service-related services or assist us in analyzing how our Service is used. These third parties have access to your Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>17. REASONABLE SECURITY PRACTICES AND PROCEDURES</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        BetygFi takes various steps and measures to protect the security of your Personal Data from misuse, loss, unauthorized access, modification or disclosure. We use latest secure server layers encryption and access control on our systems.
						<br />
						<br />
                        Our safety and security processes are audited by a third party cyber security audit agency from time to time.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>18. LINKS TO OTHER SITES</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
						<br />
						<br />
                        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
					</Text>

					<Text variant={"contentHeading3"} fontWeight={"600"} paddingTop={"30px"}>19. CHANGES TO THIS PRIVACY POLICY</Text>
					<Text variant={"content"} paddingTop={"20px"} paddingLeft={"20px"}>
                        We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
						<br />
						<br />
                        We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.
						<br />
						<br />
                        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
					</Text>
				</Box>
			</Box>
		</>
	);
};

export default PrivacyPanelComponent;



